### ISSUE TITLE
Not an issue but a wish

### ISSUE THREAD

**Issue by koburg** [djerik/wavinsentio-ha#1]
Hi

thank you for this cool adon to Home assistant

is it possible to get the humidity in as well

it would be cool to make some notifications based on the humidity.

![IMG_0371](https://user-images.githubusercontent.com/3473374/118358702-56b3d700-b580-11eb-84a4-d85ed1cf6f81.jpeg)

**Comment by djerik** [comment]
The humidity is already integrated via the component, but the standard climate card does not show it. You can check the value in Developer Tools or you can show it in a sensor card or use the Simple Thermostat card https://github.com/nervetattoo/simple-thermostat. This is a quick example I did:

`      - type: 'custom:simple-thermostat'
        entity: climate.room_1
        step_size: 1
        sensors:
          - attribute: current_humidity
            name: Humidity
        header:
        control:
          preset: true`
