### ISSUE TITLE
Multiple controllers

### ISSUE THREAD

**Issue by tomvanschelven** [djerik/wavinsentio-ha#10]
Hi, Is there anyway to control multiple controllers? We have 4 in our house for the different manifolds but currently I can only control one.

Thanks

Tom

**Comment by djerik** [comment]
I have not tested, but you should be able to add the integration multiple times. 1 for each controller. You have all 4 to chose from during configuration?

**Comment by tomvanschelven** [comment]
My Bad, your right. Thanks so much for creating this, so much better to have it all in one place!
