### ISSUE TITLE
Nothing happens after clean install

### ISSUE THREAD

**Issue by stephenson** [djerik/wavinsentio-ha#12]
Hep! Awesome that you are working on this project!

I just installed your componant and it shows up under Add Integrations, but when I click the integration it starts to set up, but nothing happens. 

Any tricks? 

<img width="539" alt="CleanShot 2022-06-21 at 20 22 14@2x" src="https://user-images.githubusercontent.com/60150/174871365-e237871c-a891-43e4-8c5b-eb3679881008.png">

Home Assistant Core 2022.6.6

**Comment by djerik** [comment]
I will have a look at it

**Comment by djerik** [comment]
I did a fresh HA installation and a fresh WavinSentio installation, and was ok at my end. Could you try again and check your logs if you still experience problems?
