### ISSUE TITLE
Lost connection to Sentio after firmware update

### ISSUE THREAD

**Issue by jskipperdk** [djerik/wavinsentio-ha#13]
Hi
I lost the connection to all devices in the Sentio. I think it might happened after updating to the latest firmware SENTIO-v12. 1-2022.10. 14.

I tried to remove the integration and readd it, but I fails with the error message "Unknown error occurred" 

I can login to the Sentio and use it as normally. 

Did anybody else experience this?

Br
Jakob

**Comment by djerik** [comment]
I have updated my HA installation to latest version and upgraded Sentio to latest firmware, and I cannot replicate this problem. Any more details from you log?
