### ISSUE TITLE
Standby Mode

### ISSUE THREAD

**Issue by BadgerLoaf** [djerik/wavinsentio-ha#15]
Thanks alot for this integration. I was wondering if it might be possible to be able to toggle the 'Stand-By Mode' setting for the house via HA?

I would really like to be able to use this to effectively turn off all the heating when required (which I currently do via the Sentio app)

Thanks for any help!

![IMG_6130](https://user-images.githubusercontent.com/108699847/204157909-d1662286-4c8e-4ca0-aad2-1f6921a519cd.jpg)

**Comment by djerik** [comment]
As I read the notes in the Sentio app;
"Location in stand-by mode maintain fixed set temperature for undefined time"
it doesn't turn off heating as you are requesting?

If you like to turn off all heating from HA, I suggest to create scenes.

**Comment by BadgerLoaf** [comment]
Yes that is correct, it puts the heating into stand-by mode, which is a low temperature that you set. It doesn't turn it off, it keeps it low for frost protection. 

Apologies for the bad wording of my initial request. It's not to do with turning it off, its to enable/disable the Stand-By Mode.

It's a mode I use on the app, so I was hoping it might be able to be accessed through the HA integration.

**Comment by mikkelmoell** [comment]
> Yes that is correct, it puts the heating into stand-by mode, which is a low temperature that you set. It doesn't turn it off, it keeps it low for frost protection.
> 
> Apologies for the bad wording of my initial request. It's not to do with turning it off, its to enable/disable the Stand-By Mode.
> 
> It's a mode I use on the app, so I was hoping it might be able to be accessed through the HA integration.

This is also a feature I would like - if possible :)

**Comment by djerik** [comment]
I think I still need to understand what you are trying to achieve?

Why is this not just handled by two scenes in HA setting the temperatures per entity? ("Frost Protection" & "Normal Heating")

**Comment by BadgerLoaf** [comment]
Hi @djerik, apologies have been away and tied up.

Agreed, that might be a possible way for alot of use cases. However, due to a couple of factors, I need to use the Sentio app for other family members, and allow that to control my heating schedule.

Therefore, if I set the heating via a scene in HA (for instance set them all to 6 degrees), it will only remain in affect until the next scheduled temp change. 

So in the Sentio app I use the Stand-By mode. Given this is a mode available in the app (and used by us outside of HA), I was hoping that it might be something that could also be viewed/used in HA.

I genuinely believe there is a need for this, giving access to a mode available in the app; however I fully appreciate this is your project to do as you wish. But if this was possible, I would be very grateful.

Thanks

**Comment by djerik** [comment]
OK - I will have a look at it soon

**Comment by BadgerLoaf** [comment]
Thank you @djerik - appreciate it

**Comment by BadgerLoaf** [comment]
Hi @djerik. I don't suppose you've had any time to take a look at this? Thanks for all your time and work on the integration.

**Comment by djerik** [comment]
Hi @BadgerLoaf 

Sorry, been working on other projects.

Done loose hope, I will get to it :)

**Comment by BadgerLoaf** [comment]
No problem @djerik, I know how life goes! No rush, happy if it's on the roadmap.

**Comment by djerik** [comment]
I found it in the api. How should it work in HA? A selector between modes (normal/standby/?) or boolean Standby on/off?

**Comment by BadgerLoaf** [comment]
Hi @djerik - great news!

I guess could be presented either way, but I would suggest a boolean Standby on/off would be most suitable, as I think that would reflect the app presentation.

**Comment by djerik** [comment]
I have added an additional standby switch entity to the platform and refactored a lot of code. Please upgrade, test and let me know
