### ISSUE TITLE
Wavin API

### ISSUE THREAD

**Issue by stephenson** [djerik/wavinsentio-ha#16]
Hi @djerik 
This has nothing to do with your great project. It works well! 

But I am considering doing something similar for [HomeBridge](https://homebridge.io/), but I can't seem to find any API information from Wavin. Did you have to reverse engineer the API from the app, or did you find some docs somewhere that my Google foo does not find?

**Comment by djerik** [comment]
The API is not documented. The best I can offer is to look in this repository and in the python wavin api client module repository. Last resort is to send me an email :)

**Comment by stephenson** [comment]
@djerik That was a fast reply! 

Thanks! 

I will play around with the code you have written, thanks a lot! And thanks for the offer!
