### ISSUE TITLE
Request - Sensors for humidity and battery

### ISSUE THREAD

**Issue by mikkelmoell** [djerik/wavinsentio-ha#17]
If possible can you add a sensor for humidity for each entity? Also could be great to a separat sensor for temperatur as well for creating nice dashboards :).
See figure below. This is from my tado radiator thermostat infomation.

![image](https://user-images.githubusercontent.com/60513050/209885589-4ab4ac69-718a-4ce5-aead-c0b36abe56a6.png)

Also if the info is available battery status. This could be used for monitor or get alerts if battery status i low.

**Comment by djerik** [comment]
Temperature and humidity is already available on the entities, but the standard climate card doesn't show it. Please see https://github.com/djerik/wavinsentio-ha/issues/14 for example.

I have not seen battery level in the api nor the App. Have you seen it?

**Comment by djerik** [comment]
I found a battery low warning attribute. Any ideas to how the entity should be? An additional bool attribute to the Climate entity? or a new bool entity per sensor? I think I prefer the first, people can then make alerts when the attribute goes true.

**Comment by djerik** [comment]
I have added battery low warning as an additional attribute
