### ISSUE TITLE
After upgrade to HA 2023.5.1, Sentio integration can't start

### ISSUE THREAD

**Issue by larserhardsen** [djerik/wavinsentio-ha#19]
The logs says the following:

Logger: homeassistant.config_entries
Source: custom_components/wavinsentio/__init__.py:39
Integration: Wavin Sentio ([documentation](https://github.com/djerik/wavinsentio-ha), [issues](https://github.com/djerik/wavinsentio-ha/issues))
First occurred: 10:18:48 (1 occurrences)
Last logged: 10:18:48
Error setting up entry Wavin Sentio for wavinsentio
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/wavinsentio/__init__.py", line 39, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by djerik** [comment]
Thank you for reporting it. I have searched, and root cause is a breaking change from HA. I hope to have fix ready within the next days

**Comment by djerik** [comment]
@larserhardsen I have fixed bug. Can you test and confirm?

**Comment by larserhardsen** [comment]
That was fast! I can confirm that the integration works again on HA 2023.5.2! Thanks!

**Comment by KasperHoldum** [comment]
Can also confirm it fixed it after updating to the newest version in HACS on 2023.5.2
