### ISSUE TITLE
Unstable connection with Wavin Sentio since Core Update October 11, 2024

### ISSUE THREAD

**Issue by Hennie-R12F** [djerik/wavinsentio-ha#26]
Seems to be related with update Core 11 October 2024

12 oktober 2024

Badkamer  is niet meer beschikbaar
06:29:37 - 5 uur geleden

Badkamer  gewijzigd in Verwarmen
06:27:37 - 5 uur geleden

Badkamer  is niet meer beschikbaar
05:57:36 - 6 uur geleden

Badkamer  gewijzigd in Verwarmen
05:53:34 - 6 uur geleden

Badkamer  is niet meer beschikbaar
05:51:28 - 6 uur geleden

Badkamer  gewijzigd in Verwarmen
05:41:27 - 6 uur geleden

Badkamer  is niet meer beschikbaar
05:35:26 - 6 uur geleden

Badkamer  gewijzigd in Verwarmen
05:33:26 - 6 uur geleden

Badkamer  is niet meer beschikbaar
05:19:24 - 7 uur geleden

Badkamer  gewijzigd in Verwarmen
03:31:17 - 8 uur geleden

Badkamer  is niet meer beschikbaar
03:27:16 - 8 uur geleden

Badkamer  gewijzigd in Verwarmen
03:17:16 - 9 uur geleden

Badkamer  is niet meer beschikbaar
03:05:16 - 9 uur geleden

11 oktober 2024

Badkamer  gewijzigd in Verwarmen
22:11:54 - 14 uur geleden

Badkamer  is niet meer beschikbaar
22:07:53 - 14 uur geleden

**Comment by Hennie-R12F** [comment]
TNX

**Comment by Hennie-R12F** [comment]
TNX

**Comment by newbenji** [comment]
Frontend error when installing on new setup

Config flow could not be loaded: {"message":"Invalid handler specified"}


Logs from container

2024-11-23 13:53:22.673 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration wavinsentio: No module named 'wavinsentio'

**Comment by newbenji** [comment]
Made requirements file
And made pip install -r requirements.txt


`/config/custom_components/wavinsentio# pip install -r requirements.txt`

**Comment by newbenji** [comment]
requirements.txt is just this line
WavinSentio==0.4.1

**Comment by newbenji** [comment]
not so experienced with this
but maybe need setup scripts like for this integration

https://github.com/MTrab/energidataservice/blob/master/scripts/setup

And the requirements file

**Comment by newbenji** [comment]
https://github.com/home-assistant/core/issues/127966

**Comment by Hennie-R12F** [comment]
Hello Mr. Benjamin Anderson,

My issue on github can be closed.
The issue did not repeat later on.

I’am a new bee. Started with Home Assistant in September last.
I tried to find out how to close my issue in October. Unsuccessful.
And then I was forgotten the issue I created.

I tried again to find out closing. Again unsuccessful.

What to do?

Thanks for this message.

Kind regards
Hennie van Apeldoorn

**Comment by newbenji** [comment]
Actually solved it also.
Showed it was running in container, so wanted empty file in the container. they changed something detection and how they create the env for python

**Comment by devboyz089** [comment]
after installing this and trying to add it, right after I click on the add integration button -> Wavin sentio plugin it gives errors:
Please wait, starting configuration wizard for Wavin Sentio (for around 1 min)
then:
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
Did anybody experienced similar?
HASS Core 2024.12.5 on RPi

**Comment by Hennie-R12F** [comment]
Correct. Today I lost th connection between HA and the Wavin Sentio integration. Also the Sentio App signals periodically no connection and advices to check the Wifi connection. The last is fine. Regards HennieOp 10 jun 2025 om 21:56 heeft Tobias Laursen ***@***.***> het volgende geschreven:﻿djerik left a comment (djerik/wavinsentio-ha#26)
Is this issue still relevant? If so please share details, and I will have a look at it

**Comment by djerik** [comment]
The WS has been migrated by Wavin. I am looking into it, but not yet sure how much time it will take
