### ISSUE TITLE
strange error humidity

### ISSUE THREAD

**Issue by koburg** [djerik/wavinsentio-ha#3]
hello

I got this error in the log. 

`Invalid config for [script]: expected a dictionary. Got OrderedDict([('default_config', {}), ('group', {}), ('automation', [OrderedDict([('id', '1621239024112'), ('alias', 'Fugtighed Garage 60'), ('description', ''), ('trigger', [OrderedDict([('platform', 'numeric_state'), ('entity_id', 'climate.room_12_garage'), ('attribute', 'current_humidity'), ('above', '60')])]), ('condition', [OrderedDict([('condition', 'time'), ('after', '14:00'), ('before', '22:00')])]), ('action', [OrderedDict([('service', 'media_player.volume_set'), ('data', OrderedDict(.... (See /config/configuration.yaml, line 5).
Invalid config for [script]: [entity_id] is an invalid option for [script]. Check: script->entity_id. (See /config/configuration.yaml, line 5).
Invalid config for [script]: [num_repeats] is an invalid option for [script]. Check: script->num_repeats. (See /config/configuration.yaml, line 5).`

I try to run automation based on humidity it seems to work I think but the log keeps popping up with this also tried to change the automation to other trigger but  same error

do you know what causing this ?

 im worried other automations won't work if this ain't 

`alias: Fugtighed Garage 60
description: ''
trigger:
  - platform: numeric_state
    entity_id: climate.room_12_garage
    attribute: current_humidity
    above: '60'
condition:
  - condition: time
    after: '14:00'
    before: '22:00'
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.kontor
  - service: notify.mobile_app_iphone_akf
    data:
      message: >-
        den aktuelle fugtighed i garage er nu på {{
        states.climate.room_12_garage.attributes.current_humidity }}%
  - service: tts.amazon_polly_say
    data:
      entity_id: media_player.kontor
      message: >-
        den aktuelle fugtighed i garage er nu på {{    
        states.climate.room_12_garage.attributes.current_humidity }}%
mode: single
`

this is from the yaml config setup the sensor

`sensor:
  - platform: template
    sensors:
      climate_humidity:
        friendly_name: "Humidity"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('climate.room_12_garage', 'current_humidity') }}"`

**Comment by koburg** [comment]
might have fixed it now changede the rule. 

But it start appear after latest update of HASS. 

and also another rule show not working which has worked and I did not change.
 so im not sure there's any thing wrong 
either than a bug in the newest HASS.

**Comment by djerik** [comment]
looks like a bug in your rule definition. Please re-open if errors are coming from the component
