### ISSUE TITLE
Showing air humidity alongside temperature

### ISSUE THREAD

**Issue by KasperHoldum** [djerik/wavinsentio-ha#5]
Hi

Awesome work on the integration with Sentio. The temperatures for the rooms are showing perfectly.

Would it be possible to add humidity for each room as well?

**Comment by djerik** [comment]
Hi Kasper

The integration already takes care of humidity. The standard climate card does however not show it. You can handle this by using another card, for example simple thermostat: https://community.home-assistant.io/t/lovelace-simple-thermostat-card/82659
