### ISSUE TITLE
outside temperature

### ISSUE THREAD

**Issue by cbjerg** [djerik/wavinsentio-ha#7]
Any way of getting the outside temperature entity on? I have it in the Sentio app,

**Comment by djerik** [comment]
Yes - I will add it tonight if all goes well. I can't test because my outdoor sensor is added to another controller, so I look forward to your feedback

**Comment by djerik** [comment]
It was a bit more complex than expected, but please test this version

**Comment by cbjerg** [comment]
Thank you - works perfectly
