### ISSUE TITLE
IR Sensors and Humidity

### ISSUE THREAD

**Issue by andersaagaard** [djerik/wavinsentio-ha#9]
Great integration.
Any plans on integrate the IR version of the thermostat ?
Would be nice to be able to control floor temperatur.

Furthermore the humidity reads from the sensor would be nice to use for controlling eg. ventilation.

**Comment by djerik** [comment]
@fedearne did the support for floor temperature and should be working. It is in extended attributes, so you probably need to modify the card or use another climate card.

Humidity has been there from day one, but the standard climate card doesn't show it.

**Comment by djerik** [comment]
No, that is not how HA is designed. Humidity is an attribute of the climate entity. You can see the value under develop tools or add a card to show current_temperature of the climate entity

**Comment by andersaagaard** [comment]
Ohh offcourse !
What about battery level and signal strength ?
And is it planned to control the floor min/max settings ?

**Comment by djerik** [comment]
I have not spotted battery level & signal strength in either the app nor the api - have you?

Why would you need to set the floor min/max from HA?
